name: TMP Dump Debug Keystore

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: Restore stable debug keystore
      uses: actions/cache@v4
      with:
        path: ~/.android/debug.keystore
        key: winlator-hdroidx-debug-keystore-v1

    - name: Upload keystore as artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-keystore
        path: ~/.android/debug.keystore